ci:
  autofix_prs: false
repos:
  - repo: "https://github.com/codespell-project/codespell"
    rev: "v2.4.1"
    hooks:
      - id: "codespell"
        args: ["--config=.codespellrc", "."]
        pass_filenames: false
  - repo: "https://github.com/pre-commit/mirrors-clang-format"
    rev: "v21.1.6"
    hooks:
      - id: "clang-format"
        types_or: ["c"]
        args: ["--style=file"]
